# Generated by Django 5.2.9 on 2026-05-10 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0034_alter_productcomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='تصویر بنر')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک مقصد')),
                ('position', models.CharField(choices=[('wide_single', 'بنر عریض میانی (حداکثر ۱ عدد)'), ('middle_half', 'بنرهای وسط صفحه (حداکثر ۲ عدد)'), ('side_grid_four', 'بنر ستون کناری (حداکثر ۴ عدد)')], max_length=50, verbose_name='جایگاه نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کمپین (مثل پیشنهاد شگفت\u200cانگیز)')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='campaigns', to='product.product', verbose_name='محصولات کمپین')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کمپین فروش ویژه',
                'verbose_name_plural': 'کمپین\u200cهای فروش ویژه',
            },
        ),
    ]
