# Generated by Django 5.2.9 on 2026-05-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='متن کوتاه'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان بنر'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(help_text='(مثل پیشنهاد شگفت\u200cانگیز)', max_length=200, verbose_name='عنوان کمپین'),
        ),
    ]
