# Generated by Django 5.2.9 on 2026-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_banner_text_alter_banner_title_alter_campaign_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش '),
        ),
    ]
