# Generated by Django 5.2.9 on 2026-09-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_banner_options_banner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='اگر جایگاهی بدون تصویر باشد،تصویر آپلود شده شما نمایش داده نخواهد شد.', upload_to='banners/%Y/%m/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='اگر جایگاه نمایش شما 1 عددی باشد ترتیب نمایش اثری نخواهد داشت.', verbose_name='ترتیب نمایش '),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('wide_single', 'بنر عریض میانی (حداکثر ۱ عدد) '), ('new_collection', 'کالکشن جدید (حداکثر ۱ عدد)(بدون تصویر)'), ('middle_half', 'بنرهای وسط صفحه (حداکثر ۲ عدد)'), ('side_grid_four', 'بنر ستون کناری (حداکثر ۴ عدد)')], max_length=50, verbose_name='جایگاه نمایش'),
        ),
    ]
