# Generated by Django 5.2.9 on 2026-05-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
