# Generated by Django 5.2.9 on 2026-05-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], db_index=True, default=2, max_length=10, verbose_name='Priority'),
        ),
    ]
