# Generated by Django 5.2.9 on 2026-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_alter_ticket_options_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['status', 'priority', '-created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], db_index=True, default=2, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Open'), (1, 'Closed')], db_index=True, default=0, verbose_name='Status'),
        ),
    ]
