# Generated by Django 5.2.9 on 2026-05-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_ticket_options_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Open'), (0, 'Closed')], db_index=True, default=1, verbose_name='Status'),
        ),
    ]
