# Generated by Django 5.2.9 on 2026-09-09 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_alter_ticket_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'دپارتمان', 'verbose_name_plural': 'دپارتمان ها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-status', 'priority', '-created_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام\u200cهای تیکت'},
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام دپارتمان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع داده شده به'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='helpdesk.department', verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'کم'), (2, 'متوسط'), (3, 'زیاد')], db_index=True, default=2, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رفرنس کد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'باز'), (0, 'بسته')], db_index=True, default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='شماره تیکت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ارسال شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='helpdesk.ticket', verbose_name='تیکت'),
        ),
    ]
