# Generated by Django 5.2.9 on 2025-12-27 06:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام برند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی والد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش دسته بندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته بندی والد',
                'verbose_name_plural': 'دسته بندی های والد',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/image/product-color/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش عکس')),
                ('is_cover', models.BooleanField(default=False, help_text='انتخاب این عکس به عنوان عکس پیش نمایش محصول داخل لیست محصولات', verbose_name='عکس کاور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس های محصولات',
            },
        ),
        migrations.CreateModel(
            name='CategoryChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی فرزند')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش دسته بندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی فرزند',
                'verbose_name_plural': 'دسته بندی های فرزند',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='مشخصات محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات/معرفی محصول')),
                ('fixed_price', models.PositiveBigIntegerField(blank=True, help_text='اگر برای این محصول قیمت ثابتی در نظر گرفته نشد،برای یکی از رنگ های آن حتما باید قیمت در نظر گرفته شود!', null=True, verbose_name='قیمت ثابت')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف ویژه این محصول')),
                ('is_published', models.BooleanField(default=True, verbose_name='وضعیت انتشار محصول')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='وضعیت محبوبیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.brand', verbose_name='برند محصول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category', verbose_name='دسته بندی محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات ',
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کدتخفیف')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('is_percentage', models.BooleanField(default=True, help_text='با غیرفعال کردن این گزینه مقدار تخفیف به تومان/ریال محاسبه میشود!', verbose_name='درصد')),
                ('max_usage', models.PositiveIntegerField(default=0, help_text='اگر تعداد حداکثر استفاده 0 باشد ،کد تا پایان زمان انقضاء حداکثر 1 بار برای تمامی کاربران قابل استفاده است!', verbose_name='حداکثر تعداد استفاده ')),
                ('current_usage', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات استفاده شده')),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2025, 12, 29, 6, 4, 51, 398088, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا')),
                ('is_all_products', models.BooleanField(default=False, help_text='با فعال کردن این گزینه، کدتخفیف شامل تمامی محصولات سایت میشود!', verbose_name='تمام محصولات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('products', models.ManyToManyField(blank=True, related_name='discount_codes', to='product.product', verbose_name='محصولات شامل این کد تخفیف')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم رنگ')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رنگ (HEX)')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت این رنگ')),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی این رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='وضعیت تایید نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
            },
        ),
    ]
