# Generated by Django 5.2.9 on 2025-12-28 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_created_by_brand_deleted_at_brand_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'کدتخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 30, 2, 55, 19, 531192, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
    ]
