# Generated by Django 5.2.9 on 2026-01-01 06:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_is_active_categorychildren_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorychildren',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/image/category-children/icon/', verbose_name='کاور دسته بندی فرزند'),
        ),
        migrations.AlterField(
            model_name='categorychildren',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='childrens', to='product.category', verbose_name='دسته بندی والد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 6, 57, 36, 644230, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی این رنگ'),
        ),
    ]
