# Generated by Django 5.2.9 on 2026-01-07 07:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productcomment_reply_alter_discountcode_expired_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='name',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 9, 7, 39, 44, 430405, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت این رنگ از محصول'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی این رنگ از محصول'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='اسم رنگ')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رنگ (HEX)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.color', verbose_name='رنگ'),
            preserve_default=False,
        ),
    ]
