# Generated by Django 5.2.9 on 2026-01-07 13:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productcolor_code_remove_productcolor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ ها '},
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='user',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام دسته بندی والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش دسته بندی'),
        ),
        migrations.AlterField(
            model_name='categorychildren',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='categorychildren',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام دسته بندی فرزند'),
        ),
        migrations.AlterField(
            model_name='categorychildren',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش دسته بندی'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 9, 13, 1, 5, 97391, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_usage',
            field=models.PositiveIntegerField(default=0, help_text='اگر تعداد حداکثر استفاده 0 باشد ،کد تا پایان زمان انقضاء حداکثر 1 بار برای تمامی کاربران قابل استفاده است! ولی اگر تعداد حداکثر بیشتر از 0 باشد تا پایان زمان انقضا کد وقتی تعداد دفعات استفاده برابر با تعداد حداکثر شداعتبار کد به پایان می رسد', verbose_name='حداکثر تعداد استفاده '),
        ),
        migrations.AlterField(
            model_name='product',
            name='fixed_price',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='اگر برای این محصول قیمت ثابتی در نظر گرفته نشد،برای یکی از رنگ های آن حتما باید قیمت در نظر گرفته شود!', null=True, verbose_name='قیمت ثابت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='وضعیت انتشار محصول'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, help_text='.اگر قیمتی برای این رنگ در نظر گرفته نشود، پیش فرض قیمت پایه محصول روی این رنگ اعمال می شود', null=True, verbose_name='قیمت این رنگ از محصول'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True, verbose_name='وضعیت تایید نظر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(db_index=True, default=False, help_text='انتخاب این عکس به عنوان عکس پیش نمایش محصول داخل لیست محصولات', verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش عکس'),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('name', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('product', 'color')},
        ),
        migrations.AddIndex(
            model_name='categorychildren',
            index=models.Index(fields=['category', 'is_active', 'is_deleted'], name='product_cat_categor_b08cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_published', 'is_deleted'], name='product_pro_categor_b7e70c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['fixed_price'], name='product_pro_fixed_p_fddebd_idx'),
        ),
    ]
