# Generated by Django 5.2.9 on 2026-01-07 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_color_options_remove_productcomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 9, 13, 13, 22, 406955, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
    ]
