# Generated by Django 5.2.9 on 2026-01-07 13:34

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_discountcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='کد رنگ (HEX)'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 9, 13, 34, 25, 379507, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
    ]
