# Generated by Django 5.2.9 on 2026-01-08 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_discountcode_expired_at_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 17, 16, 10, 266379, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fixed_price',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text='اگر برای این محصول قیمت ثابتی در نظر گرفته نشد،برای یکی از رنگ های آن حتما باید قیمت در نظر گرفته شود!', verbose_name='قیمت ثابت'),
        ),
    ]
