# Generated by Django 5.2.9 on 2026-01-09 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_discountcode_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 11, 17, 50, 6, 934947, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fixed_price',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text='!اگر قیمت ثابت محصول و یا تمام رنگ های آن 0 باشد محصول رایگان در نظر گرفته میشود', verbose_name='قیمت ثابت'),
        ),
    ]
