# Generated by Django 5.2.9 on 2026-01-22 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_brand_deleted_at_alter_brand_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 24, 8, 0, 0, 124994, tzinfo=datetime.timezone.utc), help_text='زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است!', verbose_name='زمان انقضا'),
        ),
    ]
