# Generated by Django 5.2.9 on 2026-01-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_discountcode_alter_cart_discount_code'),
        ('product', '0022_alter_discountcode_expired_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
