# Generated by Django 5.2.9 on 2026-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_delete_discountcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='percentage',
            new_name='special_discount',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='special_discount',
            field=models.PositiveIntegerField(default=0, help_text='.اگر تخفیف ویژه برای این رنگ از محصول در نظر گرفته نشود، پیش فرض تخفیف ویژه پایه محصول روی این رنگ اعمال می شود', verbose_name='درصد تخفیف ویژه این رنگ از محصول'),
        ),
    ]
