# Generated by Django 5.2.9 on 2026-02-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_rename_percentage_product_special_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='special_discount',
            new_name='discount_percentage',
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='special_discount',
            new_name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='price',
            field=models.PositiveBigIntegerField(default=0, help_text='.اگر قیمتی برای این رنگ در نظر گرفته نشود، پیش فرض قیمت پایه محصول روی این رنگ اعمال می شود', verbose_name='(تومان)قیمت این رنگ از محصول'),
        ),
    ]
