# Generated by Django 5.2.9 on 2026-02-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_rename_special_discount_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolor',
            old_name='discount_percentage',
            new_name='base_discount',
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='price',
            new_name='base_price',
        ),
    ]
