# Generated by Django 5.2.9 on 2026-02-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_discount_percentage_productcolor_base_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorychildren',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='.با فعال کردن این گزینه دسته بندی در منو دسته بندی صفحه اصلی سایت نمایش داده میشود', verbose_name='نمایش در منو'),
        ),
    ]
