# Generated by Django 5.2.9 on 2026-02-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_categorychildren_show_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorychildren',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='.با فعال کردن این گزینه دسته بندی در منوی دسته بندی صفحه اصلی سایت نمایش داده میشود', verbose_name='نمایش در منو'),
        ),
    ]
