# Generated by Django 5.2.9 on 2026-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorychildren',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/category-children/icon/', verbose_name='کاور دسته بندی فرزند'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='home/images/gallery/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/product-color/'),
        ),
    ]
