# Generated by Django 5.2.9 on 2026-05-09 17:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_categorychildren_icon_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-created_at',), 'verbose_name': 'نظر محصول', 'verbose_name_plural': 'نظرات محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات/معرفی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='مشخصات محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(db_index=True, default=False, help_text='انتخاب این عکس به عنوان عکس پیش نمایش محصول داخل لیست دیدگاه ها،علاقه مندی های کاربر وهرجایی که این محصول داخل یک لیستی قرار میگیرد.', verbose_name='عکس کاور'),
        ),
    ]
