# Generated by Django 5.2.9 on 2026-05-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
