# Generated by Django 5.2.9 on 2026-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_delete_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('order',), 'verbose_name': 'رنگ محصول', 'verbose_name_plural': 'رنگ بندی محصولات'},
        ),
        migrations.AddField(
            model_name='productcolor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='برای ترتیب نمایش این رنگ داخل صفحه جزئیات محصول', verbose_name='ترتیب نمایش رنگ'),
        ),
    ]
