# Generated by Django 5.2.9 on 2026-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_productcolor_options_productcolor_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('order', '-created_at'), 'verbose_name': 'رنگ محصول', 'verbose_name_plural': 'رنگ بندی محصولات'},
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='وضعیت تایید نظر'),
        ),
    ]
