# Generated by Django 5.2.9 on 2026-06-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_productcolor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='کد محصول'),
        ),
    ]
