# Generated by Django 5.2.9 on 2026-06-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='public_id',
            new_name='product_code',
        ),
    ]
