# Generated by Django 5.2.9 on 2026-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_rename_public_id_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('factory', 'محصولات کارخانه'), ('store', 'محصولات فروشگاه')], default='store', max_length=20, verbose_name='نوع محصول'),
        ),
    ]
