# Generated by Django 5.2.9 on 2026-06-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('store', 'محصولات فروشگاه'), ('factory', 'محصولات کارخانه')], default='store', max_length=20, verbose_name='نوع محصول'),
        ),
    ]
