from django.db import models


class ProvinceChoices(models.TextChoices):
    EAST_AZERBAIJAN = "east_azerbaijan", "آذربایجان شرقی"
    WEST_AZERBAIJAN = "west_azerbaijan", "آذربایجان غربی"
    ARDABIL = "ardabil", "اردبیل"
    ISFAHAN = "isfahan", "اصفهان"
    ALBORZ = "alborz", "البرز"
    ILAM = "ilam", "ایلام"
    BUSHEHR = "bushehr", "بوشهر"
    CHAHARMAHAL_BAKHTIARI = "chaharmahal_bakhtiari", "چهارمحال و بختیاری"
    SOUTH_KHORASAN = "south_khorasan", "خراسان جنوبی"
    RAZAVI_KHORASAN = "razavi_khorasan", "خراسان رضوی"
    NORTH_KHORASAN = "north_khorasan", "خراسان شمالی"
    KHUZESTAN = "khuzestan", "خوزستان"
    ZANJAN = "zanjan", "زنجان"
    SEMNAN = "semnan", "سمنان"
    SISTAN_BALUCHESTAN = "sistan_baluchestan", "سیستان و بلوچستان"
    FARS = "fars", "فارس"
    QAZVIN = "qazvin", "قزوین"
    QOM = "qom", "قم"
    KURDISTAN = "kurdistan", "کردستان"
    KERMAN = "kerman", "کرمان"
    KERMANSHAH = "kermanshah", "کرمانشاه"
    KOHGILUYEH_BOYER_AHMAD = "kohgiluyeh_boyer_ahmad", "کهگیلویه و بویراحمد"
    GOLESTAN = "golestan", "گلستان"
    GILAN = "gilan", "گیلان"
    LORESTAN = "lorestan", "لرستان"
    MAZANDARAN = "mazandaran", "مازندران"
    MARKAZI = "markazi", "مرکزی"
    HORMOZGAN = "hormozgan", "هرمزگان"
    HAMEDAN = "hamedan", "همدان"
    YAZD = "yazd", "یزد"
    TEHRAN = "tehran", "تهران"