# Generated by Django 5.2.9 on 2026-05-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_deleted_at_alter_blog_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(help_text='کاور بلاگ برای نمایش داخل لیست بلاگ ها', null=True, upload_to='blog/images/cover/', verbose_name='کاور بلاگ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='زمان تخمینی برای خواندن این پست وبلاگ به دقیقه.', verbose_name='زمان مطالعه بلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text_body',
            field=models.TextField(default='', verbose_name='متن بلاگ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmedia',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='blog.blog', verbose_name='وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='عکس'),
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام موضوع برند')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال/غیرفعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موضوع برند',
                'verbose_name_plural': 'موضوعات برند',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.categoryblog', verbose_name='موضوع بلاگ'),
        ),
    ]
