# Generated by Django 5.2.9 on 2026-05-02 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_cover_blog_reading_time_alter_blog_text_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmedia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogmedia',
            name='video',
        ),
        migrations.AddField(
            model_name='blogmedia',
            name='media',
            field=models.FileField(help_text='برای هر بلاگ فقط یکی از این دو رسانه(عکس یا ویدئو) رو باید انتخاب کنید.', null=True, upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mov', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AddField(
            model_name='blogmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'عکس'), ('video', 'ویدئو')], max_length=5, null=True, verbose_name='نوع رسانه'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(help_text='برای نمایش داخل لیست بلاگ ها', null=True, upload_to='blog/images/cover/', verbose_name='کاور بلاگ'),
        ),
    ]
