# Generated by Django 5.2.9 on 2026-05-02 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogmedia_image_remove_blogmedia_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='media',
            field=models.FileField(help_text='برای هر بلاگ فقط یکی از این دو رسانه(عکس یا ویدئو) رو باید انتخاب کنید.', null=True, upload_to='blog/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mov', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='رسانه'),
        ),
    ]
