# Generated by Django 5.2.9 on 2026-05-02 19:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن بلاگ'),
        ),
    ]
