# Generated by Django 5.2.9 on 2026-09-14 15:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='factory_address',
            field=models.TextField(null=True, verbose_name='آدرس کارخانه'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='footer_text',
            field=models.TextField(null=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='instagram_url',
            field=models.URLField(null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='logo',
            field=models.ImageField(null=True, upload_to='shop/images/logo/', verbose_name='لوگوی فروشگاه'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='shop_address',
            field=models.TextField(null=True, verbose_name='آدرس فروشگاه'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='support_mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره موبایل پشتیبانی'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='support_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره تلفن ثابت پشتیبانی'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='telegram_url',
            field=models.URLField(null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='maintenance_message',
            field=models.CharField(default='در حال حاضر فروش موقتاً غیرفعال است', max_length=255, verbose_name='پیام وضعیت غیرفعال'),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('media_url', models.URLField(blank=True, verbose_name='لینک رسانه')),
                ('media_file', models.FileField(blank=True, upload_to='shop/about/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mov', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='فایل رسانه')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], max_length=10, verbose_name='نوع رسانه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
