# Generated by Django 5.2.9 on 2026-09-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopsettings_factory_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='media_type',
            field=models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], help_text='نوع رسانه را مطابق با فایل یا لینک انتخاب کنید. عدم تطابق نوع رسانه با فایل یا لینک باعث نمایش اشتباه آن در وب\u200cسایت خواهد شد.', max_length=10, verbose_name='نوع رسانه'),
        ),
    ]
