# Generated by Django 5.2.9 on 2026-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_aboutus_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='support_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن ثابت پشتیبانی'),
        ),
    ]
