# Generated by Django 5.2.9 on 2026-01-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contactus_created_by_contactus_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
    ]
