# Generated by Django 5.2.9 on 2026-01-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_contactus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
