# Generated by Django 5.2.9 on 2026-02-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_contactus_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='receiver_phone_number',
            field=models.CharField(max_length=11, verbose_name='Receiver Phone Number'),
        ),
        migrations.CreateModel(
            name='OTPCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('purpose', models.CharField(choices=[('register', 'ثبت نام'), ('reset_password', 'بازیابی رمز عبور')], default='register', max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ('-last_sent_at',),
            },
        ),
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('password_hash', models.CharField(max_length=128, verbose_name='password')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sign Up Verification',
                'verbose_name_plural': 'Sign Up Verification Queue',
            },
        ),
        migrations.DeleteModel(
            name='SignUpVerifyCode',
        ),
        migrations.AddIndex(
            model_name='otpcodemodel',
            index=models.Index(fields=['phone_number', 'purpose', 'is_used'], name='user_otpcod_phone_n_0e532b_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpcodemodel',
            constraint=models.UniqueConstraint(fields=('phone_number', 'purpose'), name='unique_phone_purpose'),
        ),
    ]
