# Generated by Django 5.2.9 on 2026-02-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_birthdate_alter_user_receiver_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count_sms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify_phone_code',
        ),
    ]
