# Generated by Django 5.2.9 on 2026-03-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_product_slug'),
        ('user', '0007_remove_user_count_sms_remove_user_verify_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='interested_users', to='product.product', verbose_name='Interests'),
        ),
    ]
