# Generated by Django 5.2.9 on 2026-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_product_slug'),
        ('user', '0008_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='product.product', verbose_name='Interests'),
        ),
    ]
