# Generated by Django 5.2.9 on 2026-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(blank=True, choices=[('discount_code', 'کدتخفیف')], max_length=30, null=True, verbose_name='موضوع اعلان'),
        ),
    ]
