# Generated by Django 5.2.9 on 2026-03-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_cart_created_by'),
        ('user', '0010_notification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order.discountcode', verbose_name='کد تخفیف'),
        ),
    ]
