# Generated by Django 5.2.9 on 2026-03-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_notification_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
    ]
