# Generated by Django 5.2.9 on 2026-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_notification_options_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsession',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='registrationsession',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
