# Generated by Django 5.2.9 on 2026-09-09 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_product_product_type'),
        ('user', '0014_registrationsession_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'درخواست تماس با ما', 'verbose_name_plural': 'درخواست های تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان ها'},
        ),
        migrations.AlterModelOptions(
            name='notificationread',
            options={'verbose_name': 'وضعیت دیدن اعلان توسط کاربر', 'verbose_name_plural': 'وضعیت خوانده شدن اعلان ها توسط کاربران'},
        ),
        migrations.AlterModelOptions(
            name='otpcodemodel',
            options={'ordering': ('-last_sent_at',), 'verbose_name': 'کد ارسال شده', 'verbose_name_plural': 'کد های ارسال شده'},
        ),
        migrations.AlterModelOptions(
            name='registrationsession',
            options={'verbose_name': 'تایید ثبت نام', 'verbose_name_plural': 'صف تایید ثبت نام'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='is_called',
            field=models.BooleanField(default=False, verbose_name='تماس گرفته شده'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شده'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=75, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='user.notification', verbose_name='اعلان'),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تایم خواندن اعلان'),
        ),
        migrations.AlterField(
            model_name='notificationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='otpcodemodel',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد دفعات درخواست ارسال کد'),
        ),
        migrations.AlterField(
            model_name='otpcodemodel',
            name='code_hash',
            field=models.CharField(max_length=128, verbose_name='کد ارسال شده'),
        ),
        migrations.AlterField(
            model_name='otpcodemodel',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AlterField(
            model_name='otpcodemodel',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تایم آخرین کد ارسال شده'),
        ),
        migrations.AlterField(
            model_name='otpcodemodel',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='otpcodemodel',
            name='purpose',
            field=models.CharField(choices=[('register', 'ثبت نام'), ('reset_password', 'بازیابی رمز عبور')], default='register', max_length=20, verbose_name='دلیل درخواست کد'),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='password_hash',
            field=models.CharField(max_length=128, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='product.product', verbose_name='علاقه مندی ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/image_profiles/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='receiver_phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن دریافت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_phone_number',
            field=models.BooleanField(default=False, verbose_name='تایید شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کدپستی'),
        ),
    ]
