# Generated by Django 5.2.9 on 2026-01-22 08:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color_code',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='کد رنگ (HEX)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='قیمت پایه محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='جمع جزء(تومان)'),
        ),
    ]
