# Generated by Django 5.2.9 on 2026-01-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cartitem_count_alter_orderitem_color_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DifferentAddress',
        ),
    ]
