# Generated by Django 5.2.9 on 2026-01-26 06:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_delete_differentaddress'),
        ('product', '0022_alter_discountcode_expired_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کدتخفیف')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار تخفیف')),
                ('is_percentage', models.BooleanField(default=True, help_text='!با غیرفعال کردن این گزینه مقدار تخفیف به تومان محاسبه میشود', verbose_name='درصد')),
                ('max_usage', models.PositiveIntegerField(default=0, help_text='اگر تعداد حداکثر استفاده 0 باشد ،کد تا پایان زمان انقضاء حداکثر 1 بار برای تمامی کاربران قابل استفاده است! ولی اگر تعداد حداکثر بیشتر از 0 باشد تا پایان زمان انقضا کد وقتی تعداد دفعات استفاده برابر با تعداد حداکثر شداعتبار کد به پایان می رسد', verbose_name='حداکثر تعداد استفاده ')),
                ('current_usage', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات استفاده شده')),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2026, 1, 28, 6, 51, 21, 387825, tzinfo=datetime.timezone.utc), help_text='!زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است', verbose_name='زمان انقضا')),
                ('is_all_products', models.BooleanField(default=False, help_text='!با فعال کردن این گزینه، کدتخفیف شامل تمامی محصولات سایت میشود', verbose_name='تمام محصولات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='discount_codes', to='product.product', verbose_name='محصولات شامل این کد تخفیف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کدتخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_used', to='order.discountcode', verbose_name='کد تخفیف'),
        ),
    ]
