# Generated by Django 5.2.9 on 2026-01-26 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_discountcode_alter_cart_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='included_type',
            field=models.CharField(choices=[('cart', 'سبدخرید'), ('product', 'محصول/محصولات')], default='cart', max_length=10, verbose_name='تخفیف شامل'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 7, 4, 16, 331314, tzinfo=datetime.timezone.utc), help_text='!زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است', verbose_name='زمان انقضا'),
        ),
    ]
