# Generated by Django 5.2.9 on 2026-01-26 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_discountcode_included_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='is_all_products',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 14, 0, 35, 802315, tzinfo=datetime.timezone.utc), help_text='!زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است', verbose_name='زمان انقضا'),
        ),
    ]
