# Generated by Django 5.2.9 on 2026-02-10 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_discountcode_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discounted_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 17, 26, 45, 317665, tzinfo=datetime.timezone.utc), help_text='!زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است', verbose_name='زمان انقضا'),
        ),
    ]
