# Generated by Django 5.2.9 on 2026-02-18 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_cartitem_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('created_at',), 'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'آیتم های سبد های خرید'},
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='discounted_price',
            new_name='discounted',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 17, 13, 35, 337423, tzinfo=datetime.timezone.utc), help_text='!زمان انقضا به صورت پیش فرض دو روز بعد از زمان سیستم است', verbose_name='زمان انقضا'),
        ),
    ]
