# Generated by Django 5.2.9 on 2026-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_cart_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(default=None, max_length=255, verbose_name='کد تراكنش'),
            preserve_default=False,
        ),
    ]
