# Generated by Django 5.2.9 on 2026-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_fill_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره سفارش'),
        ),
    ]
