# Generated by Django 5.2.9 on 2026-05-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderitem_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_pay', 'در انتظار پرداخت'), ('doing', 'در حال آماده سازی'), ('send', 'ارسال شده'), ('completing', 'تکمیل شده'), ('canceled', 'لغو شده')], default='pending_pay', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
