# Generated by Django 5.2.9 on 2026-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدار تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_scope',
            field=models.CharField(blank=True, choices=[('cart', 'سبد خرید'), ('product', 'محصول')], max_length=15, null=True, verbose_name='دامنه اعمال کد'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'درصد'), ('amount', 'تومان')], max_length=10, null=True, verbose_name='نوع مقدار تخفیف'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف پایه محصول(تومان)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف کد روی آیتم(تومان)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ نهایی آیتم(تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_pay', 'در انتظار پرداخت'), ('pay_error', 'خطا در حین پرداخت'), ('paid', 'پرداخت شده'), ('pending_review', 'در انتظار بررسی'), ('doing', 'در حال آماده سازی'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending_pay', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد تراكنش'),
        ),
    ]
