# Generated by Django 5.2.9 on 2026-05-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_discount_amount_order_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('payment_timeout', 'اتمام زمان پرداخت'), ('payment_error', 'خطا در پرداخت'), ('admin_cancelled', 'لغو توسط ادمین'), ('customer_request', 'درخواست مشتری')], max_length=50, null=True, verbose_name='دلیل لغو سفارش توسط ادمین'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_color_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_pay', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('pending_review', 'در انتظار بررسی'), ('doing', 'در حال آماده سازی'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending_pay', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
