# Generated by Django 5.2.9 on 2026-05-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_cancel_reason_orderitem_product_color_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات لغو سفارش توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('payment_timeout', 'اتمام زمان پرداخت'), ('payment_error', 'خطا در پرداخت'), ('admin_cancelled', 'لغو توسط ادمین'), ('customer_request', 'درخواست مشتری')], max_length=50, null=True, verbose_name='دلیل لغو سفارش'),
        ),
    ]
