# Generated by Django 5.2.9 on 2026-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_cancel_description_alter_order_cancel_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='base_discount_amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مجموع تخفیف پایه محصول(تومان)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ تخفیف پایه محصول (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('payment_timeout', 'اتمام زمان پرداخت'), ('payment_error', 'خطا در پرداخت'), ('admin_cancelled', 'لغو توسط ادمین'), ('customer_request', 'لغو توسط مشتری')], max_length=50, null=True, verbose_name='دلیل لغو سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_pay', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('pending_review', 'در انتظار بررسی'), ('doing', 'در حال آماده سازی'), ('shipped', 'ارسال شده'), ('cancelled', 'لغو شده')], default='pending_pay', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
