# Generated by Django 5.2.9 on 2026-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_remove_orderitem_base_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='cost',
        ),
        migrations.AddField(
            model_name='delivery',
            name='inter_province_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال برون استان(تومان)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='intra_province_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال درون استان(تومان)'),
        ),
    ]
