# Generated by Django 5.2.9 on 2026-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_delivery_cost_delivery_inter_province_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='inter_province_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه ارسال بیرون استان(تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, choices=[('east_azerbaijan', 'آذربایجان شرقی'), ('west_azerbaijan', 'آذربایجان غربی'), ('ardabil', 'اردبیل'), ('isfahan', 'اصفهان'), ('alborz', 'البرز'), ('ilam', 'ایلام'), ('bushehr', 'بوشهر'), ('chaharmahal_bakhtiari', 'چهارمحال و بختیاری'), ('south_khorasan', 'خراسان جنوبی'), ('razavi_khorasan', 'خراسان رضوی'), ('north_khorasan', 'خراسان شمالی'), ('khuzestan', 'خوزستان'), ('zanjan', 'زنجان'), ('semnan', 'سمنان'), ('sistan_baluchestan', 'سیستان و بلوچستان'), ('fars', 'فارس'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('kurdistan', 'کردستان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('kohgiluyeh_boyer_ahmad', 'کهگیلویه و بویراحمد'), ('golestan', 'گلستان'), ('gilan', 'گیلان'), ('lorestan', 'لرستان'), ('mazandaran', 'مازندران'), ('markazi', 'مرکزی'), ('hormozgan', 'هرمزگان'), ('hamedan', 'همدان'), ('yazd', 'یزد'), ('tehran', 'تهران')], max_length=50, null=True, verbose_name='استان'),
        ),
    ]
