# Generated by Django 5.2.9 on 2026-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_fix_order_province_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='نوع ارسال'),
        ),
    ]
