# Generated by Django 5.2.9 on 2026-09-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pending_pay', 'در انتظار پرداخت'), ('pay_doing', 'در حال پرداخت'), ('pay', 'پرداخت شده'), ('pay_error', 'خطا در حین پرداخت')], default='pending_pay', max_length=20, verbose_name='وضعیت پرداخت سبد خرید'),
        ),
    ]
